// Build the single-file host bundle that the Rust binary embeds.
//
// `dist/` is committed so `cargo build` never needs Node or npm; CI rebuilds
// and fails on drift (`git diff --exit-code dist`).
import { build } from 'esbuild'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outdir = join(here, 'dist')
mkdirSync(outdir, { recursive: true })

const hostBuild = await build({
  entryPoints: [join(here, 'src/main.ts')],
  outfile: join(outdir, 'codewhale-extension-host.mjs'),
  absWorkingDir: here,
  metafile: true,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  // Deterministic output: no sourcemap paths, no timestamps, no minification
  // (a readable bundle keeps the reviewed-bytes story honest).
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: {
    js: '// codewhale-extension-host — generated by crates/tui/extension-host/build.mjs; do not edit.\n// Third-party notices: LICENSES.txt next to this file.',
  },
})

// Test-only protocol module (codec + validators) so `node --test` can check
// the corpus against the exact code the host runs, without booting a host.
// Not embedded in the Rust binary.
await build({
  entryPoints: [join(here, 'src/protocol.ts')],
  outfile: join(outdir, 'protocol.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.19',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'warning',
  banner: { js: '// generated by crates/tui/extension-host/build.mjs from src/protocol.ts; do not edit.' },
})


// Third-party notices (`dist/LICENSES.txt`), generated from what the bundler
// actually put in the host bundle: every package that contributed an input
// file, with its own LICENSE file. A package added to or dropped from the
// bundle changes this file, and CI's `git diff --exit-code -- dist` then
// catches a stale one. The Rust core embeds this file and writes it beside the
// materialised bundle, so the banner's promise ("LICENSES.txt next to this
// file") holds for every installed copy.
const LICENSE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'LICENCE.md', 'license', 'license.md', 'COPYING']

function bundledPackages(metafile) {
  const found = new Map()
  for (const input of Object.keys(metafile.inputs)) {
    const marker = 'node_modules/'
    const at = input.lastIndexOf(marker)
    if (at < 0) continue
    const [first, second] = input.slice(at + marker.length).split('/')
    const name = first.startsWith('@') ? `${first}/${second}` : first
    found.set(name, join(here, input.slice(0, at + marker.length), name))
  }
  return [...found.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([name, root]) => ({ name, root }))
}

function readLicense(root, label) {
  for (const file of LICENSE_FILES) {
    try {
      return readFileSync(join(root, file), 'utf8').trim()
    } catch {}
  }
  throw new Error(`${label} is bundled but ships no LICENSE file in ${root}; add its notice by hand before releasing`)
}

// Source vendored into `src/` verbatim rather than imported from node_modules.
// The metafile cannot see these, so each names the file that carries the
// excerpt and the bundled package whose licence text it shares (checked below).
const EXCERPTED = [
  {
    name: '@deepseek-ai/dsh-tools',
    version: '0.1.7-alpha.2',
    license: 'MIT',
    file: 'src/dsh/dsh-tools-compat.js',
    licenseOf: '@deepseek-ai/dsh-util-values',
  },
]

const packages = bundledPackages(hostBuild.metafile).map(({ name, root }) => {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  if (typeof pkg.license !== 'string' || pkg.license.length === 0) throw new Error(`${name} declares no license in package.json`)
  return { name: pkg.name, version: pkg.version, license: pkg.license, text: readLicense(root, name) }
})
if (packages.length === 0) throw new Error('the host bundle contains no node_modules input: the notice generator is reading the wrong metafile')

const entries = packages.map((pkg) => ({ ...pkg, note: '' }))
for (const excerpt of EXCERPTED) {
  const source = readFileSync(join(here, excerpt.file), 'utf8')
  if (!source.includes(`${excerpt.name}@${excerpt.version}`)) {
    throw new Error(`${excerpt.file} no longer names ${excerpt.name}@${excerpt.version}; update EXCERPTED in build.mjs`)
  }
  const shared = packages.find((pkg) => pkg.name === excerpt.licenseOf)
  if (!shared) throw new Error(`${excerpt.licenseOf} (licence text of ${excerpt.name}) is not bundled`)
  entries.push({
    name: excerpt.name,
    version: excerpt.version,
    license: excerpt.license,
    text: shared.text,
    note: `Verbatim excerpts of this package are in ${excerpt.file}, under the same licence text as ${excerpt.licenseOf} above.`,
  })
}
entries.sort((a, b) => (a.name < b.name ? -1 : 1))

const sections = [
  'Third-party software bundled into codewhale-extension-host.mjs.',
  'Generated by crates/tui/extension-host/build.mjs from the bundler metafile; do not edit.',
  '',
  'Packages:',
  ...entries.map((entry) => `  ${entry.name}@${entry.version} (${entry.license})`),
]
for (const entry of entries) {
  sections.push('', '='.repeat(72), `${entry.name}@${entry.version} (${entry.license})`, '='.repeat(72))
  if (entry.note) sections.push('', entry.note)
  sections.push('', entry.text)
}
writeFileSync(join(outdir, 'LICENSES.txt'), sections.join('\n') + '\n')
